#!/usr/bin/env ruby

ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)

require "bundler/setup"

$LOAD_PATH.unshift(File.expand_path("../lib", __dir__))

require "kamal_backup"

KamalBackup::CLI.start
